# Generated by Django 3.1.2 on 2020-10-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201020_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='in_active',
            new_name='in_archive',
        ),
    ]
